CUDA_VISIBLE_DEVICES=1 python run_classifier.py \
--data_dir glue_data/CoLA/ \
--task_name cola \
--train_batch_size 32 \
--max_seq_length 128 \
--bert_model bert-base-uncased \
--learning_rate 2e-5 \
--num_train_epochs 2 \
--do_train \
--do_eval \
--do_lower_case \
--max_num_aspect 3 \
--output_dir glue/cola_model_dir
