CUDA_VISIBLE_DEVICES=1 python run_classifier.py \
--data_dir data/intention2_v2/ \
--task_name cola \
--train_batch_size 32 \
--max_seq_length 102 \
--bert_model bert-base-chinese \
--learning_rate 2e-5 \
--num_train_epochs 5 \
--do_train \
--do_eval \
--do_lower_case \
--max_num_aspect 3 \
--output_dir glue/intention_model_dir
